//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_QLKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaKho
    {
        public NhaKho()
        {
            this.LoHangs = new HashSet<LoHang>();
            this.VitriSuas = new HashSet<VitriSua>();
        }
    
        public int ID_NhaKho { get; set; }
        public Nullable<int> SoTang { get; set; }
        public Nullable<int> SoHang { get; set; }
        public Nullable<int> SoCot { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<LoHang> LoHangs { get; set; }
        public virtual ICollection<VitriSua> VitriSuas { get; set; }
    }
}
