//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_QLKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomHangHoa
    {
        public NhomHangHoa()
        {
            this.HangHoas = new HashSet<HangHoa>();
        }
    
        public string ID_NHH { get; set; }
        public string TenNHH { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}
