//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_QLKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.LoHangs = new HashSet<LoHang>();
        }
    
        public int ID_PhieuNhap { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string ID_NhanVien { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<LoHang> LoHangs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
