//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_QLKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_XuatKho
    {
        public int ID_CT { get; set; }
        public Nullable<int> ID_PhieuXuat { get; set; }
        public Nullable<int> MaLoHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Note { get; set; }
    
        public virtual LoHang LoHang { get; set; }
        public virtual PhieuXuat PhieuXuat { get; set; }
    }
}
