//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_QLKHO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbQLKhoEntities : DbContext
    {
        public dbQLKhoEntities()
            : base("name=dbQLKhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CT_XuatKho> CT_XuatKho { get; set; }
        public DbSet<HangHoa> HangHoas { get; set; }
        public DbSet<LoHang> LoHangs { get; set; }
        public DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public DbSet<NhaKho> NhaKhoes { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<NhomHangHoa> NhomHangHoas { get; set; }
        public DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public DbSet<PhieuXuat> PhieuXuats { get; set; }
        public DbSet<VitriSua> VitriSuas { get; set; }
    }
}
