//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_QLKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public PhieuXuat()
        {
            this.CT_XuatKho = new HashSet<CT_XuatKho>();
        }
    
        public int ID_PhieuXuat { get; set; }
        public string ID_NhanVien { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<CT_XuatKho> CT_XuatKho { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
